# Generated by Django 6.0.7 on 2026-07-26 16:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('matricula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('curso', models.CharField(max_length=255)),
                ('periodo', models.IntegerField()),
                ('turma', models.CharField(max_length=255)),
                ('ingresso', models.DateField()),
                ('nota', models.FloatField()),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pai', models.CharField(max_length=255)),
                ('mae', models.CharField(max_length=255)),
                ('telefone_responsavel', models.CharField(max_length=255)),
                ('email_responsavel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data_de_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laudo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('ano_diagnostico', models.IntegerField()),
                ('atendimento_fora_da_escola', models.CharField()),
                ('texto_atendimento', models.TextField()),
                ('estudante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.TextField()),
                ('pergunta', models.TextField()),
                ('texto', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField()),
                ('descricao', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_curricular', models.TextField()),
                ('adaptacao_curricular', models.TextField()),
                ('habilidade', models.TextField()),
                ('facilidade_dificuldade', models.TextField()),
                ('metas_turma', models.TextField()),
                ('metas_especifica', models.TextField()),
                ('procedimento_metodologico', models.TextField()),
                ('avaliacao', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('texto2', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.TextField()),
                ('habilidade', models.TextField()),
                ('nao_gosta', models.TextField()),
                ('dificuldade', models.TextField()),
                ('informacao', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.TextField()),
                ('metas_curto_prazo', models.TextField()),
                ('metas_medio_prazo', models.TextField()),
                ('metas_longo_prazo', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='PEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.professor')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.professor')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
