from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.cadastro),
    path('cadastro_sistema/', views.cadastro_sistema, name="cadastro_sistema"),
    path('cadastro_estudante/', views.cadastro_estudante, name="cadastro_estudante"),
    path('cadastro_professor/', views.cadastro_professor, name="cadastro_professor"),
    path('cadastro_funcionario/', views.cadastro_funcionario, name="cadastro_funcionario"),
    path('PEI/', views.pei, name="pei"),
    path('cadastro_equipe/', views.cadastro_equipe, name="cadastro_equipe"),
    path('diagnostico/', views.diagnostico, name="diagnostico"),
    path('historico_escolar/', views.historico_escolar, name="historico_escolar"),
    path('perfil_estudante/', views.perfil_estudante, name="perfil_estudante"),
    path("atividade/", views.atividade, name="atividade"),
    path("planejamento/", views.planejamento, name="planejamento"),
    path("checklist2/", views.checklist2, name="checklist2"),
    path("habilidade_academica/", views.habilidade_academica, name="habilidade_academica"),
    path("gerar_pdf/", views.gerar_pdf, name="gerar_pdf"),
    path("login1/", views.login1, name="login1"),
    path("sair/", views.sair, name="sair"),
    path("painel_administrador/", views.painel_administrador, name="painel_administrador"),
    path("estudante_cadastrado/", views.estudante_cadastrado, name="estudante_cadastrado"),
    path("remover_estudante/", views.remover_estudante, name="remover_estudante"),
    path("remover_professor/", views.remover_professor, name="remover_professor"),
    path("remover_funcionario/", views.remover_funcionario, name="remover_funcionario"),
    path("professor_cadastrado/", views.professor_cadastrado, name="professor_cadastrado"),
    path("funcionario_cadastrado/", views.funcionario_cadastrado, name="funcionario_cadastrado"),
    path("gerenciar_professor/", views.gerenciar_professor, name="gerenciar_professor"),
    path("gerenciar_funcionario/", views.gerenciar_funcionario, name="gerenciar_funcionario"),
    path("gerenciar_estudante/", views.gerenciar_estudante, name="gerenciar_estudante"),
    path("remover_pei/<str:matricula>/", views.remover_pei, name="remover_pei"),
    path("remover_diagnostico/<str:matricula>/", views.remover_diagnostico, name="remover_diagnostico"),
    path("remover_historico_escolar/<str:matricula>/", views.remover_historico_escolar, name="remover_historico_escolar"),
    path("remover_perfil_estudante/<str:matricula>/", views.remover_perfil_estudante, name="remover_perfil_estudante"),
    path("remover_checklist/<str:matricula>/<int:id1>/", views.remover_checklist, name="remover_checklist"),
    path("remover_atividade/<str:matricula>/", views.remover_atividade, name="remover_atividade"),
    path("remover_planejamento/<str:matricula>/", views.remover_planejamento, name="remover_planejamento"),
    path("remover_equipe_pei/<str:matricula>/", views.remover_equipe_pei, name="remover_equipe_pei"),
    path("remover_habilidade_academica/<str:matricula>/", views.remover_habilidade_academica, name="remover_habilidade_academica"),
    path("dados_pei/<str:matricula>/", views.dados_pei, name="dados_pei"),
    path("editar_pei/<str:matricula>/", views.editar_pei, name="editar_pei"),
    path("editar_equipe_pei/<str:matricula>", views.editar_equipe_pei, name="editar_equipe_pei"),
    path("editar_diagnostico/<str:matricula>/", views.editar_diagnostico, name="editar_diagnostico"),
    path("editar_historico_escolar/<str:matricula>/", views.editar_historico_escolar, name="editar_historico_escolar"),
    path("editar_perfil_estudante/<str:matricula>/", views.editar_perfil_estudante, name="editar_perfil_estudante"),
    path("editar_checklist/<str:matricula>/<int:id1>", views.editar_checklist, name="editar_checklist"),
    path("editar_atividade/<str:matricula>/", views.editar_atividade, name="editar_atividade"),
    path("editar_planejamento/<str:matricula>/", views.editar_planejamento, name="editar_planejamento"),
    path("editar_habilidade_academica/<str:matricula>/", views.editar_habilidade_academica, name="editar_habilidade_academica"),
    path("gerenciar_pei/", views.gerenciar_pei, name="gerenciar_pei"),
    path("gerenciar_pei_matricula/", views.gerenciar_pei_matricula, name="gerenciar_pei_matricula"),
    path("editar_professor/<str:matricula>/", views.editar_professor, name="editar_professor"),
    path("editar_funcionario/<str:cpf>/", views.editar_funcionario, name="editar_funcionario"),
    path("editar_estudante/<str:matricula>/", views.editar_estudante, name="editar_estudante"),
    path("editar_professor_matricula/", views.editar_professor_matricula, name="editar_professor_matricula"),
    path("editar_funcionario_cpf/", views.editar_funcionario_cpf, name="editar_funcionario_cpf"),
    path("editar_estudante_matricula/", views.editar_estudante_matricula, name="editar_estudante_matricula")
]

